Add Ci and automated code formatter as well as linting tool
ie3-institute/MarkovsHousehold pull request #50
Opened 2022-04-07 15:48 UTC by t-ober

Resolves #49

With flake8 you can test your code formatting from the command line with `flake8`.
With black typing `black .` in the command line should resolve all code formatting issues (this works like spotless).

2022-06-20 12:35 UTC, sebastian-peter requested changes
If I may express a wish, it'd be to also inlcude [isort](https://github.com/PyCQA/isort) :)
It can be [configured](https://pycqa.github.io/isort/docs/configuration/black_compatibility.html) to nicely play together with black.

2022-07-08 10:39 UTC, t-ober commented on .flake8
> +[flake8]
I did adjust the configuration as suggested in the [documentation](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html) to make them work together

2022-07-08 10:45 UTC, t-ober commented on docs/sphinx/conf.py
> +)
True

2022-07-08 11:01 UTC, t-ober commented on docs/sphinx/conf.py
> +)
Would have to look a little further. Have opened an issue https://github.com/ie3-institute/MarkovsHousehold/issues/58

2022-07-28 10:53 UTC, sebastian-peter requested changes
Some minor remarks

2022-07-28 10:53 UTC, sebastian-peter commented on pyproject.toml
> +flake8-isort = "^4.1.1"
Wouldn't these better fit inside `dev-dependencies` below? Which also applies to all other dependencies here besides `python` and `pyyaml`, I think

2022-07-28 10:53 UTC, sebastian-peter commented on .flake8
> +[flake8]
Hmm, well black and flake8 do not _conflict_ now, in the sense that one does not reverse changes of the other or vice versa.
But, they do not use the same code style for checking/correcting. Black is applying stricter rules than flake8 is checking for. So to make them consistent, I thought of using the plugin above... Kind of like `spotlessCheck` complains about style violations _excatly_ when `spotlessApply` would fix these violations.

2022-08-12 12:38 UTC, sebastian-peter commented on .github/workflows/simple-ci.yml
> +         poetry run black --check .
Add flake8 again since black does not cover all its tests?

2022-08-12 18:09 UTC, sebastian-peter approved these changes
Thanks!

2022-08-12 18:09 UTC, merged